### ISSUE TITLE
Suggestion - better declaration for "then" and "or"

### ISSUE THREAD

**Issue by edwinyzh** [enko/DelphiVerbalExpressions#2]
Hello Tim,

I'm just copying a suggestion people made [in this discussion](https://plus.google.com/u/0/115143382472228750230/posts/fYmLwhXg6EL): 

> Great! But, I think you could declare &Then() and &Or() instead of _Then() and _Or()

That way, you can use the keywords as method names :)

Well done, BTW, I found your implementation before I deciding to write my own :)

**Comment by enko** [comment]
Hey @edwinyzh ,

I just saw that I still have this repository and saw your issue, will change this code. But I have to say, that I do not use Delphi any more.
